#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

npm run test
test_result=$?
if [ $test_result -ne 0 ]; then
  echo "Tests failed. Aborting commit."
  exit 1
fi
echo -e "\nThe tests were passed successfully"

# Prettify all selected files
echo -e "\nPrettifying selected files:"
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

echo -e "\nValidating Javascript & Typescript with eslint:"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
eslint_result=$?
if [ $eslint_result -ne 0 ]; then
  echo "ESLint found errors. Aborting commit."
  exit 1
fi
echo -e "Javascript & Typescript validation completed."

# Compile all TypeScript files to check for errors
echo -e "\nCompiling all Javascript & Typescript files to check for errors:"
./node_modules/.bin/tsc --noEmit --skipLibCheck
tsc_result=$?
if [ $tsc_result -ne 0 ]; then
  echo "JavaScript & Typescript compilation errors found. Aborting commit."
  exit 1
fi
echo -e "No compilation errors found."

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add
echo "$STAGED_FILES" | xargs git add

exit $?